- name: hiding the name 
  hosts: developer
  vars_prompt:
    - name: username
      prompt: "What is your name?"
      private: false
  
  tasks:
    - name: printing the username
      ansible.builtin.debug:
        msg: "Print the name: {{ username }}"


- name: hiding the password 
  hosts: developer
  vars_prompt:
    - name: password
      prompt: "What is your password?"
      private: true
  
  tasks:
    - name: printing the password
      ansible.builtin.debug:
        msg: "Print the password: {{ password }}"
