       
- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0def8440e04260e46 # replace with your SG ID
    zone_id: "Z04942961NBG75UTT7C0L" # replace with your ID
    domain_name: "eswar.xyz"
    instances:
      - mango
    # we can pass instances through command line using -e
    # instances: 
    # - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output


  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"


  - name: printing public ip address
    ansible.builtin.debug:
     msg: "{{item.instance[0].public_ip_address}}"

    loop: "{{ec2_output.result}}"
     