- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0def8440e04260e46 # replace with your SG ID
    zone_id: "Z04942961NBG75UTT7C0L" # replace with your ID
    domain_name: "eswar.xyz"
    instances:
    # i am commneting this and we are directly write creation of ec2 through cli console
       - mongodb
       - mysql
       - redis
      
    # we can pass instances through command line using -e
    # instances: 
    # - mongodb
    # - redis
    # - mysql
    # - rabbitmq

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output


    # - name: print the ec2_output
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_output }}"


    - name: create route53 record
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}" # mongodb.daws86s.fun
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"