- name: create ec2 and r53
  hosts: localhost
  connection: local

  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0def8440e04260e46
    zone_id: "Z04942961NBG75UTT7C0L"
    domain_name: "eswar.xyz"
    instances:
      - mongodb
      - mysql
      - redis

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: create route53 record
      amazon.aws.route53:
        state: present
        zone: "{{ zone_id }}"   # FIXED
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instance[0].private_ip_address }}"   # FIXED
        overwrite: true
      loop: "{{ ec2_output.results }}"   # FIXED
