- name: Creating MongoDB
  hosts: mongodb
  become: yes

  tasks:
    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB using dnf
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Update MongoDB config to allow external connections
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'

    - name: Start and enable MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
