- name: advanced loop programme
  hosts: dev
  become: yes
  tasks:
    - name: advanced loop programming
      ansible.builtin.package:
       name: "{{item.name}}"
       state: "{{latest.state}}"

      loop:
       - {name: "nginx", state: "absent" }
       - {name: "mysql" , state: "absent"}
     