- name: advanced loop programme
  hosts: dev
  become: yes
  tasks:
    - name: advanced loop programming
      ansible.builtin.package:
       name: "{{item.name}}"
       state: "{{item.state}}"

      # loop:
      #  - {name: "nginx", state: "absent" }
      #  - {name: "mysql" , state: "absent"}  this is for unstall the two commands

        # loop:
        # - {name: "nginx", state: "latest" }
        # - {name: "mysql" , state: "latest"} this is used for install the pacakages: