- name: basic loop staructure 
  hosts: dev
  becomes: yes
  tasks:
   - name: i am writing basic loop structure
     ansible.builtin.debug:
      msg: "Hello {{item}}"
    
   - loop:
      eswar
      reddy
      vatti




