- name: converting yaml data to json format
  hosts: dev
  become: yes

  tasks:
    - name: read and convert yaml data
      ansible.builtin.set_fact:
        student_data: "{{ lookup('file', 'student.yaml') | from_yaml }}"

    - name: print data in json format
      ansible.builtin.debug:
        msg: "{{ student_data | to_json }}"
