- name: loop programme i am writing
  hosts: dev
  become: yes

  tasks:
     - name: i am writing and installing basic programming
       ansible.builtin.package:
        name: "{{item}}"
        state: latest

       loop:
        - {name: "nginx", state: "latest"}
        - {name: "python", state: "latest"}
        - {name: "java" , state: "latest" }
