- name: converting upper to lower and lower to upper
  hosts: dev
  vars:
   Name: Eswar Reddy
   Course: JAVA
   ip address: "172.98.8.0"


  tasks:
    - name: here we can converting lower to upper
      ansible.builtin.debug:
       msg: "{{Name | upper}}"

    - name: here we can convert upper to lower
      ansible.builtin.debug:
       msg: "{{Course | lower }}"


    - name: cross checking the ip
      ansible.builtin.debug:
       msg: "{{ip address | ansible.utils.ipv4}}"